### ISSUE TITLE
securityheaders.io seems to be down but securityheaders.com is working

### ISSUE THREAD

**Issue by Choc13** [marcuslindblom/security-headers#1]
This is most likely temporary, but https://securityheaders.io is not working at the moment, however https://securityheaders.com is currently working. I wonder whether this action should try both. I'm not sure which one is the canonical domain or whether securityheaders.io will be back up.

**Comment by marcuslindblom** [comment]
I think .com is the canonical domain so I think it's safe to just skip the .io domain.

**Comment by Choc13** [comment]
OK, I've opened #2 to fix this. It was actually very straight forward to try both, but let me know on there if you'd rather it just called `.com`

**Comment by Choc13** [comment]
[According to](https://twitter.com/Matt_Choc13/status/1415385173261266944?s=20) the site's maintainer Scott Helme `.com` is canonical domain and `.io` should redirect there anyway, so I'll update the PR to just call `.com`.

**Comment by Choc13** [comment]
Thanks for merging. What are you release plans for this? Will you release this as `1.0.2` or bundle it in with the other PR as `1.1.0`?

**Comment by marcuslindblom** [comment]
After reviewing your changes I do a 1.1.0 release with both changes.
