### ISSUE TITLE
Include option to follow redirects

### ISSUE THREAD

**Issue by Choc13** [marcuslindblom/security-headers#3]
SecurityHeaders offers the `followRedirects` URL param which can take the value `on` in order to follow redirects. I think this parameter should be exposed in the action too. Happy to open a PR for it.

**Comment by marcuslindblom** [comment]
I agree, that would be great 👏🏻

**Comment by Choc13** [comment]
Cool. I've got a PR ready, but will wait until #1 is merged first before opening it to avoid the otherwise inevitable merge conflicts.
